"""empty message

Revision ID: 32ce1823715d
Revises: 3be246c8ce91
Create Date: 2014-11-09 10:50:40.006163

"""

# revision identifiers, used by Alembic.
revision = '32ce1823715d'
down_revision = '3be246c8ce91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fav_color')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fav_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
