"""empty message

Revision ID: 3be246c8ce91
Revises: f8a129574f8
Create Date: 2014-11-08 21:20:09.554971

"""

# revision identifiers, used by Alembic.
revision = '3be246c8ce91'
down_revision = 'f8a129574f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fav_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fav_color')
    ### end Alembic commands ###
